/**
 
INSERT INTO blood_stock (blood_bank_id_fk, blood_type, quantity, createdAt, updatedAt) VALUES
(1, 'A+', 10, NOW(), NOW()),
(1, 'O-', 5, NOW(), NOW()),
(2, 'B+', 8, NOW(), NOW()),
(2, 'AB-', 3, NOW(), NOW()),
(3, 'A-', 6, NOW(), NOW()),
(3, 'O+', 12, NOW(), NOW()),
(4, 'B-', 9, NOW(), NOW()),
(4, 'AB+', 4, NOW(), NOW()),
(5, 'A+', 7, NOW(), NOW()),
(5, 'O-', 2, NOW(), NOW()),
(6, 'B+', 11, NOW(), NOW()),
(6, 'AB-', 5, NOW(), NOW()),
(7, 'A-', 3, NOW(), NOW()),
(7, 'O+', 15, NOW(), NOW()),
(8, 'B-', 6, NOW(), NOW()),
(8, 'AB+', 2, NOW(), NOW()),
(9, 'A+', 14, NOW(), NOW()),
(9, 'O-', 7, NOW(), NOW()),
(10, 'B+', 4, NOW(), NOW()),
(10, 'AB-', 8, NOW(), NOW()),
(11, 'A-', 10, NOW(), NOW()),
(11, 'O+', 5, NOW(), NOW()),
(12, 'B-', 9, NOW(), NOW()),
(12, 'AB+', 12, NOW(), NOW()),
(13, 'A+', 6, NOW(), NOW()),
(13, 'O-', 3, NOW(), NOW()),
(14, 'B+', 11, NOW(), NOW()),
(14, 'AB-', 2, NOW(), NOW()),
(15, 'A-', 8, NOW(), NOW()),
(15, 'O+', 13, NOW(), NOW()),
(16, 'B-', 5, NOW(), NOW()),
(16, 'AB+', 7, NOW(), NOW()),
(17, 'A+', 12, NOW(), NOW()),
(17, 'O-', 4, NOW(), NOW()),
(18, 'B+', 9, NOW(), NOW()),
(18, 'AB-', 6, NOW(), NOW()),
(19, 'A-', 7, NOW(), NOW()),
(19, 'O+', 10, NOW(), NOW()),
(20, 'B-', 11, NOW(), NOW()),
(20, 'AB+', 8, NOW(), NOW());
 */