/**

INSERT INTO orders (user_id_fk, blood_bank_id_fk, blood_type, quantity, status, urgency_level, delivery_method, createdAt, updatedAt) VALUES
(1, 5, 'A+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(2, 7, 'O-', 1, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(3, 10, 'B+', 3, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(4, 12, 'AB-', 1, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(5, 3, 'O+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(6, 8, 'A-', 4, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(7, 9, 'B-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(8, 11, 'AB+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(9, 6, 'A+', 3, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(10, 2, 'O-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(11, 14, 'B+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(12, 16, 'AB-', 1, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(13, 18, 'O+', 3, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(14, 1, 'A-', 4, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(15, 4, 'B-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(16, 13, 'AB+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(17, 15, 'A+', 3, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(18, 19, 'O-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(19, 20, 'B+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(20, 17, 'AB-', 1, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(1, 6, 'O+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(2, 3, 'A-', 4, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(3, 8, 'B-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(4, 10, 'AB+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(5, 12, 'A+', 3, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(6, 1, 'O-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(7, 15, 'B+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(8, 17, 'AB-', 1, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(9, 14, 'O+', 3, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(10, 5, 'A-', 4, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(11, 9, 'B-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(12, 11, 'AB+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(13, 16, 'A+', 3, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(14, 18, 'O-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(15, 7, 'B+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(16, 4, 'AB-', 1, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(17, 13, 'O+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(18, 19, 'A-', 4, 'PENDING', 'URGENT', 'DELIVERY', NOW(), NOW()),
(19, 2, 'B-', 1, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW()),
(20, 20, 'AB+', 2, 'PENDING', 'NORMAL', 'PICKUP', NOW(), NOW());


 */