
/*
INSERT INTO users (full_name, email, phone, password, state, district, address, user_type, createdAt, updatedAt) VALUES
('Amit Sharma', 'amit.sharma@example.com', '9123000001', '1234', 'Maharashtra', 'Nashik', 'College Road, Nashik', 'person', NOW(), NOW()),
('Priya Verma', 'priya.verma@example.com', '9123000002', '1234', 'Maharashtra', 'Nashik', 'Sharanpur Road, Nashik', 'person', NOW(), NOW()),
('Rajesh Kumar', 'rajesh.kumar@example.com', '9123000003', '1234', 'Maharashtra', 'Nashik', 'MG Road, Nashik', 'person', NOW(), NOW()),
('Neha Gupta', 'neha.gupta@example.com', '9123000004', '1234', 'Maharashtra', 'Nashik', 'Gangapur Road, Nashik', 'person', NOW(), NOW()),
('Vikram Singh', 'vikram.singh@example.com', '9123000005', '1234', 'Maharashtra', 'Nashik', 'Canada Corner, Nashik', 'person', NOW(), NOW()),
('Sanya Mehta', 'sanya.mehta@example.com', '9123000006', '1234', 'Maharashtra', 'Nashik', 'Rane Nagar, Nashik', 'person', NOW(), NOW()),
('Aditya Rao', 'aditya.rao@example.com', '9123000007', '1234', 'Maharashtra', 'Nashik', 'College Road, Nashik', 'hospital', NOW(), NOW()),
('Pooja Kulkarni', 'pooja.kulkarni@example.com', '9123000008', '1234', 'Maharashtra', 'Nashik', 'Satpur MIDC, Nashik', 'person', NOW(), NOW()),
('Ravi Desai', 'ravi.desai@example.com', '9123000009', '1234', 'Maharashtra', 'Nashik', 'Dwarka Circle, Nashik', 'hospital', NOW(), NOW()),
('Ananya Joshi', 'ananya.joshi@example.com', '9123000010', '1234', 'Maharashtra', 'Nashik', 'Pandit Colony, Nashik', 'person', NOW(), NOW()),
('Manoj Chavan', 'manoj.chavan@example.com', '9123000011', '1234', 'Maharashtra', 'Nashik', 'Indira Nagar, Nashik', 'hospital', NOW(), NOW()),
('Kiran Bhosale', 'kiran.bhosale@example.com', '9123000012', '1234', 'Maharashtra', 'Nashik', 'College Road, Nashik', 'person', NOW(), NOW()),
('Sunil Patil', 'sunil.patil@example.com', '9123000013', '1234', 'Maharashtra', 'Nashik', 'Bytco Point, Nashik', 'hospital', NOW(), NOW()),
('Swati Jadhav', 'swati.jadhav@example.com', '9123000014', '1234', 'Maharashtra', 'Nashik', 'Canada Corner, Nashik', 'person', NOW(), NOW()),
('Arjun Reddy', 'arjun.reddy@example.com', '9123000015', '1234', 'Maharashtra', 'Nashik', 'Panchavati, Nashik', 'hospital', NOW(), NOW()),
('Rahul Khanna', 'rahul.khanna@example.com', '9123000016', '1234', 'Maharashtra', 'Nashik', 'College Road, Nashik', 'person', NOW(), NOW()),
('Deepika Sen', 'deepika.sen@example.com', '9123000017', '1234', 'Maharashtra', 'Nashik', 'Sharanpur Road, Nashik', 'hospital', NOW(), NOW()),
('Ajay Nair', 'ajay.nair@example.com', '9123000018', '1234', 'Maharashtra', 'Nashik', 'Satpur, Nashik', 'person', NOW(), NOW()),
('Sneha Dixit', 'sneha.dixit@example.com', '9123000019', '1234', 'Maharashtra', 'Nashik', 'Canada Corner, Nashik', 'hospital', NOW(), NOW()),
('Yashwant Iyer', 'yashwant.iyer@example.com', '9123000020', '1234', 'Maharashtra', 'Nashik', 'MG Road, Nashik', 'person', NOW(), NOW()),
('Harshita Kapoor', 'harshita.kapoor@example.com', '9123000021', '1234', 'Maharashtra', 'Nashik', 'Gangapur Road, Nashik', 'person', NOW(), NOW()),
('Vinod Mishra', 'vinod.mishra@example.com', '9123000022', '1234', 'Maharashtra', 'Nashik', 'Indira Nagar, Nashik', 'hospital', NOW(), NOW()),
('Kajal Bhatt', 'kajal.bhatt@example.com', '9123000023', '1234', 'Maharashtra', 'Nashik', 'MG Road, Nashik', 'person', NOW(), NOW()),
('Rajeev Nanda', 'rajeev.nanda@example.com', '9123000024', '1234', 'Maharashtra', 'Nashik', 'Panchavati, Nashik', 'hospital', NOW(), NOW()),
('Anil Yadav', 'anil.yadav@example.com', '9123000025', '1234', 'Maharashtra', 'Nashik', 'Satpur MIDC, Nashik', 'person', NOW(), NOW()),
('Tina Sinha', 'tina.sinha@example.com', '9123000026', '1234', 'Maharashtra', 'Nashik', 'College Road, Nashik', 'hospital', NOW(), NOW()),
('Mahesh Ghosh', 'mahesh.ghosh@example.com', '9123000027', '1234', 'Maharashtra', 'Nashik', 'Sharanpur Road, Nashik', 'person', NOW(), NOW()),
('Reema Pandey', 'reema.pandey@example.com', '9123000028', '1234', 'Maharashtra', 'Nashik', 'Gangapur Road, Nashik', 'hospital', NOW(), NOW()),
('Varun Kamat', 'varun.kamat@example.com', '9123000029', '1234', 'Maharashtra', 'Nashik', 'Dwarka Circle, Nashik', 'person', NOW(), NOW()),
('Madhavi Deshpande', 'madhavi.deshpande@example.com', '9123000030', '1234', 'Maharashtra', 'Nashik', 'Pandit Colony, Nashik', 'hospital', NOW(), NOW());
*/